name: wifi
description: Flutter plugin providing WiFi.
homepage: https://github.com/JoDeveloper/wifi
version: 0.1.5

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ly.wifi
    pluginClass: WifiPlugin

environment:
  sdk: ">=2.17.0 <3.0.0"
